- type: job
  id: Inspector
  name: job-name-inspector
  description: job-description-inspector
  playTimeTracker: JobInspector
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hrs
  startingGear: InspectorGear
  icon: "Inspector"
  supervisors: job-supervisors-captain
  access:
    - Service
    - Brig
    - Maintenance
    - Command

- type: startingGear
  id: InspectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerGood # TODO change to inspector jumpsuit
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsLaceup
    id: InspectorPDA
    ears: ClothingHeadsetAltSecurity
    pocket1: BookSpaceLaws
    underwearb: ClothingUnderwearBottomBoxersWhite # White-Underwear
  underweart: ClothingUnderwearTopBraWhite # White-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # White-Underwear
  inhand:
    right hand: BriefcaseBrownFilled
  innerclothingskirt: ClothingUniformJumpskirtInspector
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
